name: Android CI

on:
  push:
    branches: [ "master", "ci-1.14.0-rc04-benchmark" ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
      - '.idea/**'
      - 'fastlane/**'
      - '!.github/workflows/**'
  pull_request:
    branches: [ "master", "ci-1.14.0-rc04-benchmark" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate baseline profile
        run: ./gradlew :benchmark:Pixel5Api31StableChannelRichCodecBenchmarkAndroidTest --rerun-tasks -P android.testInstrumentationRunnerArguments.class=com.m3u.benchmark.BaselineProfileGenerator

      - name: Copy and Rename baseline profile
        run: cp benchmark/build/outputs/managed_device_android_test_additional_output/benchmark/flavours/stableChannelRichCodec/Pixel5Api31/BaselineProfileGenerator_generateBaselineProfile-baseline-prof.txt androidApp/src/main/baseline-prof.txt

      - name: Build with Gradle
        run: ./gradlew :androidApp:assembleSnapshotChannelRichCodecRelease

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: "androidApp/build/outputs/apk/snapshotChannelRichCodec/release/*.apk"

      - name: Upload To Telegram
        if: github.event_name != 'pull_request'
        uses: xireiki/channel-post@v1.0.7
        with:
          bot_token: ${{ secrets.BOT_TOKEN }}
          chat_id: ${{ secrets.CHAT_ID }}
#          large_file: true
          method: sendFile
          path: "androidApp/build/outputs/apk/snapshotChannelRichCodec/release/*.apk"
#          parse_mode: Markdown